### ISSUE TITLE
如何设置生成的文字在背景图片的中间？

### ISSUE THREAD

**Issue by Hi-Shan** [Sanster/text_renderer#16]

**Comment by Sanster** [comment]
可以把 perspective_transform 都设置成 0
```
perspective_transform:
  max_x: 0
  max_y: 0
  max_z: 0
```

如果要完全居中还可以可以把[这一行](https://github.com/Sanster/text_renderer/blob/master/textrenderer/renderer.py#L168)代码改成
```python
#  dst_height = random.randint(self.out_height // 4 * 3, self.out_height)
 dst_height = self.out_height
```
