### ISSUE TITLE
添加背景

### ISSUE THREAD

**Issue by ecetang** [Sanster/text_renderer#5]
请问一下，已在bg文件夹中添加自己的彩色背景图后，生成数据并不是添加的背景，只是普通的白底，这是为什么呢

**Comment by Sanster** [comment]
配置里面默认是 50% 的比例，你可以先设置成 1（即100%） 试试。
```yaml
img_bg:
  enable: true
  fraction: 0.5
```

最终文字的背景是从 bg 文件夹的图里随机 crop 的。
