### ISSUE TITLE
关于字体颜色的问题

### ISSUE THREAD

**Issue by xumoremore** [Sanster/text_renderer#72]
请问，为什么作者的readme是有展示可以调整字体颜色的，但是在程序里却找不到设置字体颜色的接口，如果要调整字体颜色可以在哪里改呢

**Comment by Sanster** [comment]
default.yaml 里面有配置的

```yaml
font_color:
  enable: false
  blue:
    fraction: 0.5
    l_boundary: [0,0,150]
    h_boundary: [60,60,255]
  brown:
    fraction: 0.5
    l_boundary: [139,70,19]
    h_boundary: [160,82,43]
```
